# -*- coding: utf-8 -*-
"""Actividad_2_Numpy_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ja_UbQZRejMVEHsAw9umw-VIAWzP-6pw

# Consigna
- Eliminar las columnas con información de id de sesiones, id de dispositivos, lenguaje, localización, calidad de playback y cantidad de interacciones
- Genero preferido por los hombres
- Corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
- Las edades que suelen pagar más Premium
- El video que tiene más tiempo de reproducción
- El género que más le gustó a las mujeres (rating)

Recurso: streaming.csv
"""

import pandas as pd
import numpy as np

import io
from google.colab import files
pd.set_option('display.float_format', lambda x: '%.2f' % x) # truco para notación cientifica

# from google
uploaded = files.upload()

df = pd.read_csv(io.StringIO(uploaded['streaming.csv'].decode('utf-8')))
df.head(10)

#eliminar id de sesiones, id de dispositivos, lenguaje, localización, calidad de playback y cantidad de interacciones
eliminar = ['Session_ID', 'Device_ID', 'Languages', 'Location', 'Playback_Quality', 'Interaction_Events'] #col que no queiro
df_eliminar = df #copia por si aca
df_eliminar = df_eliminar.drop(eliminar, axis=1) #drop de las que no quiero
df_eliminar

#Genero preferido por los hombres
#filtro por MALE
masculino = df[df['Gender']== 'Male']
masculino

max_masculino = masculino['Genre'].value_counts().max()
preferido = masculino['Genre'].value_counts()[masculino['Genre'].value_counts() == max_masculino].index[0]
print ('El género mas visto por los hombres es', preferido)

#corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
mas_utilizado_dispositivos = df['Device_Type'].value_counts().max()
dispo = df['Device_Type'].value_counts()[df['Device_Type'].value_counts()== mas_utilizado_dispositivos].index[0]


if dispo == 'Smartphone':
  print ('El dispositivo más utilizado es el Smartphone')
else:
  print ('EL dispositivo más utilizado es', dispo)

#Las edades que suelen pagar más Premium

premium = df[df['Subscription_Status']== 'Premium']
premium.head(5)

edad_media_promedio = premium['Age'].mean()
print('La edad promedio que suele pagar premium es',edad_media_promedio)

#no se si pedías cual era el promedio de edad o cual eran las edades mas comunes que pagan la suscripción Premium, así que pongo las dos

edad_mas_comun = premium['Age'].value_counts().idxmax()
print('La edad más común para pagar la suscripción Premium es',edad_mas_comun)

#El video que tiene más tiempo de reproducción

max_repro = df['Duration_Watched (minutes)'].max()
max_repro

#El género que más le gustó a las mujeres (rating)
femenino_df = df[df['Gender']=='Female'] #saco un df con solo mujeres
#femenino_df
mujeres_genero = femenino_df.groupby('Genre')['Ratings'].mean()
mujeres_genero

res=mujeres_genero.index[0]
print('El género que más le ha gustado a las mujeres ha sido', res)